# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MonkeyPlanner < Formula
  desc "Local-first task memory for your AI coding agents. MCP server for Claude Code, Cursor, and Continue."
  homepage "https://github.com/kjm99d/MonkeyPlanner"
  version "1.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjm99d/MonkeyPlanner/releases/download/v1.4.2/monkey-planner_1.4.2_macOS_amd64.tar.gz"
      sha256 "d64c0951cd6a6b2b5a524c535b156ee94e823d7d10706a3aab5f063abdcaf402"

      define_method(:install) do
        bin.install "monkey-planner"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjm99d/MonkeyPlanner/releases/download/v1.4.2/monkey-planner_1.4.2_macOS_arm64.tar.gz"
      sha256 "d4735e1060c257b495a64d218af767df387b6619f5b4f3bbf53d0f1a40740294"

      define_method(:install) do
        bin.install "monkey-planner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjm99d/MonkeyPlanner/releases/download/v1.4.2/monkey-planner_1.4.2_linux_amd64.tar.gz"
      sha256 "401cf8a4812411cfac48c4a5d32bb4c8910a61187b2b42acbe4940aca8d79e18"
      define_method(:install) do
        bin.install "monkey-planner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjm99d/MonkeyPlanner/releases/download/v1.4.2/monkey-planner_1.4.2_linux_arm64.tar.gz"
      sha256 "ec2d777695216b076fa955d80571445904726c716db5492d5dd3f1cc54c19897"
      define_method(:install) do
        bin.install "monkey-planner"
      end
    end
  end

  test do
    system "#{bin}/monkey-planner", "--help"
  end
end
